import { type NextPage } from "next";
import Head from "next/head";
import { config } from "~/config";
import { AppLayout } from "~/page-components/AppLayout";
import { Dashboard } from "~/page-components/Dashboard";
import { getAuthenticatedServerSideProps } from "~/server/auth";
import { api } from "~/utils/api";

const InventoryPage: NextPage = () => {
  const { data: transactionsQuery, isLoading: isTransactionsQueryLoading } =
    api.transactions.getAll.useQuery({ search: "" });

  return (
    <>
      <Head>
        <title>{config.app.title} - Inventory</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <Dashboard />
      </AppLayout>
    </>
  );
};

export {
  getAuthenticatedServerSideProps as getServerSideProps,
  InventoryPage as default,
};
