import React, { useState, useMemo } from "react";
import { type NextPage } from "next";
import Head from "next/head";
import * as Popover from "@radix-ui/react-popover";
import { IoClose } from "react-icons/io5";
import { Command } from "cmdk";
import { config } from "~/config";
import {
  Autocomplete,
  AutocompleteOption,
  Button,
  TextInput,
} from "~/components";
import { AppLayout } from "~/page-components/AppLayout";
import { api } from "~/utils/api";
import { getAuthenticatedServerSideProps } from "~/server/auth";

// <Autocomplete items={items} onSelect={} onCreate={} option={} placeholder={{ input: '' }}><Button></Autocomplete>

const OrdersNew: NextPage = () => {
  const [input, setInput] = useState("");

  const { data, isLoading, error } = api.inventory.getAll.useQuery({
    search: input,
  });

  type Item = NonNullable<typeof data>["items"][number];

  const options: AutocompleteOption<Item>[] = useMemo(() => {
    return (data?.items ?? []).map((item) => {
      return { label: item.name, value: item.id, meta: item };
    });
  }, [data]);

  const [items, setItems] = useState([]);

  const handleSelect = (_: string, option: Item) => {
    return [...items, option];
  };

  return (
    <>
      <Head>
        <title>{config.app.title} - Orders</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <div className="mx-auto w-[1280px] px-2">
          <div className="flex gap-12">
            <div className="w-full">
              <div className="flex items-center justify-between">
                <h2 className="text-2xl">New Purchase Order</h2>

                <div>
                  <Autocomplete<Item>
                    options={options}
                    option={({ meta: item }) => (
                      <div className="flex items-center gap-2 rounded px-2 py-2 group-aria-selected:bg-neutral-500">
                        {item.thumbnailUrl ? (
                          <img
                            src={item.thumbnailUrl}
                            className="h-[24px] w-[24px] rounded"
                          />
                        ) : (
                          <div className="h-[24px] w-[24px] rounded bg-neutral-500 group-aria-selected:bg-neutral-400" />
                        )}

                        <div className="flex items-center gap-1">
                          <span className="text-neutral-300 group-aria-selected:text-white">
                            {item.name}
                          </span>
                          <span className="text-neutral-500 group-aria-selected:text-neutral-300">
                            ({item.quantity})
                          </span>
                        </div>
                      </div>
                    )}
                    isLoading={isLoading}
                    error={error}
                    onSelect={handleSelect}
                  >
                    <Button type="button" variant="primary">
                      Add Item
                    </Button>
                  </Autocomplete>
                </div>
              </div>

              <div className="mb-8"></div>

              <div>
                {items.map((item, i) => (
                  <div
                    className="border-b-none flex items-center border-t border-l border-r border-neutral-700 bg-neutral-800 px-4 py-4 first:rounded-tl first:rounded-tr last:rounded-br last:rounded-bl last:border-b"
                    key={i}
                  >
                    <div className="flex w-[400px] shrink-0 items-center gap-4">
                      <div className="h-[120px] w-[120px] rounded bg-neutral-500"></div>
                      <div>
                        <h4 className="font-medium">Sereese Milky Boost</h4>
                        <div className="mb-2"></div>
                        <span className="text-neutral-400">
                          5 units / 500.00 price
                        </span>
                      </div>
                    </div>

                    <div className="w-[140px] shrink-0">
                      <h4 className="text-neutral-400">Quantity</h4>
                      <div className="mb-2"></div>
                      <span className="font-medium">5 pcs</span>
                    </div>

                    <div className="w-[140px] shrink-0">
                      <h4 className="text-neutral-400">Price</h4>
                      <div className="mb-2"></div>
                      <span className="font-medium">500.00</span>
                    </div>

                    <div className="w-[140px] shrink-0">
                      <h4 className="text-neutral-400">Total</h4>
                      <div className="mb-2"></div>
                      <span className="font-medium">2,430.00</span>
                    </div>

                    <div className="w-full">
                      <button
                        type="button"
                        className="flex h-[24px] w-[24px] items-center justify-center rounded-full bg-neutral-500"
                      >
                        <IoClose />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="w-[360px] shrink-0">
              <div className="flex h-[40px] items-center">
                <h2 className="transform text-2xl">Order Summary</h2>
              </div>

              <div className="mb-8"></div>

              <div className="rounded border border-neutral-700 bg-neutral-800 px-4 py-4">
                <div>
                  <label className="font-medium text-neutral-400">
                    Customer
                  </label>
                  <div className="mb-4"></div>
                  <TextInput placeholder="Search for a customer" />
                </div>

                <div className="mb-8"></div>

                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <label className="font-medium text-neutral-400">
                      Total Sales
                    </label>

                    <div>2,320.00</div>
                  </div>
                  <div className="flex items-center justify-between">
                    <label className="font-medium text-neutral-400">
                      Expected Profit
                    </label>

                    <div>2,320.00</div>
                  </div>
                  <div className="flex items-center justify-between">
                    <label className="font-medium text-neutral-400">
                      Total Profit
                    </label>

                    <div>2,320.00</div>
                  </div>
                </div>

                <div className="mb-8"></div>

                <Button full variant="primary">
                  Confirm Purchase Order
                </Button>
              </div>
            </div>
          </div>
        </div>
      </AppLayout>
    </>
  );
};

export {
  getAuthenticatedServerSideProps as getServerSideProps,
  OrdersNew as default,
};
